lines = [
    'from django.urls import path, include',
    'from . import views',
    '',
    'urlpatterns = [',
    '',
    '    # =============================',
    '    # CKEditor',
    '    # =============================',
    "    path('ckeditor/', include('ckeditor_uploader.urls')),",
    '',
    '    # =============================',
    '    # Core Quran APIs',
    '    # =============================',
    '    path("api/quran/", views.get_surah_ayat, name="get-surah-ayat"),',
    '    path("api/ayat/", views.get_ayat, name="get-ayat"),',
    "    path('quran-proxy/<int:ayah_number>/<str:edition>/', views.quran_ayah_proxy),",
    "    path('api/quran/search/', views.search_ayat, name='search_ayat'),",
    "    path('api/quran/search-by-root/', views.search_by_root, name='search_by_root'),",
    '    # =============================',
    '    # Fonts',
    '    # =============================',
    '    path("api/fonts/css/", views.custom_fonts_css, name="fonts_css"),',
    '    path("api/fonts/", views.get_custom_fonts, name="get-fonts"),',
    '',
    '    # =============================',
    '    # Translations',
    '    # =============================',
    '    path("api/translations/", views.get_translations, name="get_translations"),',
    '    path("api/authors/translations/", views.get_translation_authors, name="get_translation_authors"),',
    '',
    '    # =============================',
    '    # Tafseer',
    '    # =============================',
    '    path("api/tafseer/", views.get_tafseer, name="get-tafseer"),',
    '    path("api/authors/tafseer/", views.get_tafseer_authors, name="get_tafseer_authors"),',
    '    path("api/tafseer/full/", views.get_full_surah_tafseer, name="get_full_surah_tafseer"),',
    '',
    '    # =============================',
    '    # Surah Audio',
    '    # =============================',
    '    path("api/surah-audios/", views.get_surah_audios, name="get_surah_audios"),',
    '    path("api/qaris/", views.get_qaris, name="get_qaris"),',
    '',
    '    # =============================',
    '    # Word Timings',
    '    # =============================',
    '    path("api/word-timings/", views.get_word_timings, name="get_word_timings"),',
    '',
    ']',
    '',
]

with open('/home/ubuntu/apps/dawat-o-islaah-server/quran/urls.py', 'w') as f:
    f.write('\n'.join(lines))

print('Done')
